{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "2854ed26-5e2c-42ba-8dbc-e1da3697c296",
   "metadata": {},
   "outputs": [],
   "source": [
    "import torch \n",
    "import torch.nn as nn\n",
    "import numpy as np\n",
    "from torchvision.utils import save_image,make_grid\n",
    "import matplotlib.pyplot as plt\n",
    "from matplotlib.animation import FuncAnimation, PillowWriter\n",
    "import os\n",
    "import torchvision.transforms as transforms\n",
    "from torch.utils.data import Dataset\n",
    "from PIL import Image"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "5c11cef6-ebe7-4b6c-bee5-ae66552bb46a",
   "metadata": {},
   "outputs": [],
   "source": [
    "class ResidualConvBlock(nn.Module):\n",
    "    def __init__(self,in_channels,out_channels,is_res=False):\n",
    "        super().__init__()\n",
    "        self.same_channels=in_channels==out_channels\n",
    "        self.is_res=is_res\n",
    "\n",
    "        self.conv1=nn.Sequential(\n",
    "            nn.Conv2d(in_channels,out_channels,3,1,1),\n",
    "            nn.BatchNorm2d(out_channels),\n",
    "            nn.GELU(),\n",
    "        )\n",
    "\n",
    "        self.conv2=nn.Sequential(\n",
    "            nn.Conv2d(out_channels,out_channels,3,1,1),\n",
    "            nn.BatchNorm2d(out_channels),\n",
    "            nn.GELU(),\n",
    "        )\n",
    "\n",
    "\n",
    "    def forward(self,x):\n",
    "        if self.is_res:\n",
    "            x1=self.conv1(x)\n",
    "            x2=self.conv2(x1)\n",
    "\n",
    "            if self.same_channels:\n",
    "                out=x+x2\n",
    "            else:\n",
    "                shortcut=nn.Conv2D(x.shape[1],x.shape[1],kernel_size=1,stride=1,padding=0).to(x.device)\n",
    "                out=shortcut(x)+x2\n",
    "            return out/1.414\n",
    "        else:\n",
    "            x1=self.conv1(x)\n",
    "            x2=self.con2(x1)\n",
    "            return x2\n",
    "\n",
    "    def get_out_channels(self):\n",
    "        return self.conv2[0].out_channels\n",
    "\n",
    "    def set_out_channels(self,out_channels):\n",
    "        self.conv1[0].out_channels=out_channels\n",
    "        self.conv2[0].in_channels=out_channels\n",
    "        self.conv2[0].out_channels=out_channels\n",
    "\n",
    "            \n",
    "            \n",
    "        "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "056e2513-7d73-437f-b520-6e1ed4ad1526",
   "metadata": {},
   "outputs": [],
   "source": [
    "class UnwtUp(nn.Module):\n",
    "    def __init__(self,in_channels,out_channels):\n",
    "        super(UnetUp,self).__init__()\n",
    "        layers=[\n",
    "            nn.ConvTranspose2d(in_channels,out_channels,2,2),\n",
    "            ResidualConvBlock(out_channels,out_channels),\n",
    "            ResidualConvBlock(out_channels,out_channels),\n",
    "        ]\n",
    "\n",
    "        self.model=nn.Sequential(*layers)\n",
    "\n",
    "    def forward(self,x,skip):\n",
    "        x=torch.cat((x,skip),1)\n",
    "        x=self.model(x)\n",
    "        return x\n",
    "        "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "a1040dce-b85a-4af2-a1e1-e341808f3c5e",
   "metadata": {},
   "outputs": [],
   "source": [
    "class UnetDown(nn.Module):\n",
    "    def __init__(self,in_channels,out_channels):\n",
    "        super(UnetDown,self).__init__()\n",
    "\n",
    "        layers=[\n",
    "            ResidualConvBlock(in_channels,out_channels),\n",
    "            ResidualConvBlock(out_channels,out_channels),\n",
    "            nn.MaxPool2d(2)\n",
    "        ]\n",
    "        self.model=nn.Sequential(*layers)\n",
    "\n",
    "\n",
    "    def forward(self,x):\n",
    "        return self.model(x)\n",
    "\n",
    "    \n",
    "        "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "7094719a-707b-4f87-a442-3cacd7eb496e",
   "metadata": {},
   "outputs": [],
   "source": [
    "class EmbedFC(nn.Module):\n",
    "    def __init__(self,input_dim,emb_dim):\n",
    "        self.input_dim=input_dim\n",
    "        layers=[\n",
    "            nn.Linear(input_dim,emb_dim),\n",
    "            nn.GELU(),\n",
    "            nn.Linear(emb_dim,emb_dim),\n",
    "        ]\n",
    "        self.model=nn.Sequential(*layers)\n",
    "\n",
    "\n",
    "    def forward(self,x):\n",
    "        x=x.view(-1,self,input_dim)\n",
    "        return self.model(x)\n",
    "\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "7ec8b27f-cc04-48f1-8f29-c8c9fc9b1192",
   "metadata": {},
   "outputs": [],
   "source": [
    "def unorm(x):\n",
    "    xmax=x.max((0,1))\n",
    "    xmin=x.min((0,1))\n",
    "    return (x-xmin)/(xmax-xmin)\n",
    "\n",
    "\n",
    "def norm_all(store,n_t,n_s):\n",
    "    nstore=np.zeros_like(store)\n",
    "    for t in range(n_t):\n",
    "        for s in range(n_s):\n",
    "            nstore[t,s]=unorm(store[t,s])\n",
    "    return nstore\n",
    "\n",
    "\n",
    "def norm_torch(x_all):\n",
    "    x=x_all.cpu().numpy()\n",
    "    xmax=x.max((2,3))\n",
    "    xmin=x.min((2,3))\n",
    "    xmax=np.expand_dims(xmax,(2,3))\n",
    "    xmin=np.expand_dims(xmin,(2,3))\n",
    "    nstore=(x-xmin)/(xmax-xmin)\n",
    "    return torch.from_numpy(nstore)\n",
    "\n",
    "\n",
    "def gen_tst_context(n_cfeat):\n",
    "    vec=torch.tensor([\n",
    "        [1,0,0,0,0], [0,1,0,0,0], [0,0,1,0,0], [0,0,0,1,0], [0,0,0,0,1],  [0,0,0,0,0],      # human, non-human, food, spell, side-facing\n",
    "    [1,0,0,0,0], [0,1,0,0,0], [0,0,1,0,0], [0,0,0,1,0], [0,0,0,0,1],  [0,0,0,0,0],      # human, non-human, food, spell, side-facing\n",
    "    [1,0,0,0,0], [0,1,0,0,0], [0,0,1,0,0], [0,0,0,1,0], [0,0,0,0,1],  [0,0,0,0,0],      # human, non-human, food, spell, side-facing\n",
    "    [1,0,0,0,0], [0,1,0,0,0], [0,0,1,0,0], [0,0,0,1,0], [0,0,0,0,1],  [0,0,0,0,0],      # human, non-human, food, spell, side-facing\n",
    "    [1,0,0,0,0], [0,1,0,0,0], [0,0,1,0,0], [0,0,0,1,0], [0,0,0,0,1],  [0,0,0,0,0],      # human, non-human, food, spell, side-facing\n",
    "    [1,0,0,0,0], [0,1,0,0,0], [0,0,1,0,0], [0,0,0,1,0], [0,0,0,0,1],  [0,0,0,0,0]]      # human, non-human, food, spell, side-facing\n",
    "    )\n",
    "\n",
    "    return len(vec),vec\n",
    "\n",
    "def plot_grid(x,n_sample,n_rows,save_dir,w):\n",
    "    n_cols=n_sample//n_rows\n",
    "    grid=make_grid(norm_torch(x),nrow=ncols)\n",
    "    save_image(grid,save_dir+f'run_image{w}.png')\n",
    "    return grid\n",
    "\n",
    "\n",
    "def plot_sample(x_gen_store,n_sample,nrows,save_dir, fn,  w, save=False):\n",
    "    ncols = n_sample//nrows\n",
    "    sx_gen_store = np.moveaxis(x_gen_store,2,4)                               # change to Numpy image format (h,w,channels) vs (channels,h,w)\n",
    "    nsx_gen_store = norm_all(sx_gen_store, sx_gen_store.shape[0], n_sample)   # unity norm to put in range [0,1] for np.imshow\n",
    "    \n",
    "    # create gif of images evolving over time, based on x_gen_store\n",
    "    fig, axs = plt.subplots(nrows=nrows, ncols=ncols, sharex=True, sharey=True,figsize=(ncols,nrows))\n",
    "    def animate_diff(i, store):\n",
    "        print(f'gif animating frame {i} of {store.shape[0]}', end='\\r')\n",
    "        plots = []\n",
    "        for row in range(nrows):\n",
    "            for col in range(ncols):\n",
    "                axs[row, col].clear()\n",
    "                axs[row, col].set_xticks([])\n",
    "                axs[row, col].set_yticks([])\n",
    "                plots.append(axs[row, col].imshow(store[i,(row*ncols)+col]))\n",
    "        return plots\n",
    "    ani = FuncAnimation(fig, animate_diff, fargs=[nsx_gen_store],  interval=200, blit=False, repeat=True, frames=nsx_gen_store.shape[0]) \n",
    "    plt.close()\n",
    "    if save:\n",
    "        ani.save(save_dir + f\"{fn}_w{w}.gif\", dpi=100, writer=PillowWriter(fps=5))\n",
    "        print('saved gif at ' + save_dir + f\"{fn}_w{w}.gif\")\n",
    "    return ani\n",
    "    \n",
    "        \n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "a6f5a5d9-76da-4ec9-a898-a9bcee6af37e",
   "metadata": {},
   "outputs": [],
   "source": [
    "class CustomDataset(Dataset):\n",
    "    def __init__(self, sfilename, lfilename, transform, null_context=False):\n",
    "        self.sprites = np.load(sfilename)\n",
    "        self.slabels = np.load(lfilename)\n",
    "        print(f\"sprite shape: {self.sprites.shape}\")\n",
    "        print(f\"labels shape: {self.slabels.shape}\")\n",
    "        self.transform = transform\n",
    "        self.null_context = null_context\n",
    "        self.sprites_shape = self.sprites.shape\n",
    "        self.slabel_shape = self.slabels.shape\n",
    "                \n",
    "    # Return the number of images in the dataset\n",
    "    def __len__(self):\n",
    "        return len(self.sprites)\n",
    "    \n",
    "    # Get the image and label at a given index\n",
    "    def __getitem__(self, idx):\n",
    "        # Return the image and label as a tuple\n",
    "        if self.transform:\n",
    "            image = self.transform(self.sprites[idx])\n",
    "            if self.null_context:\n",
    "                label = torch.tensor(0).to(torch.int64)\n",
    "            else:\n",
    "                label = torch.tensor(self.slabels[idx]).to(torch.int64)\n",
    "        return (image, label)\n",
    "\n",
    "    def getshapes(self):\n",
    "        # return shapes of data and labels\n",
    "        return self.sprites_shape, self.slabel_shape\n",
    "\n",
    "transform = transforms.Compose([\n",
    "    transforms.ToTensor(),                # from [0,255] to range [0.0,1.0]\n",
    "    transforms.Normalize((0.5,), (0.5,))  # range [-1,1]\n",
    "\n",
    "])\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.14.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
